"""
main.py
-------
FastAPI inference server for the AI / Human text detector.

Endpoints
---------
GET  /health            liveness probe
POST /predict           paragraph or article prediction
POST /predict/batch     multiple texts in one call (optional)
GET  /model/info        metadata about the loaded model

Run locally
-----------
    uvicorn main:app --reload --host 0.0.0.0 --port 8000

With Docker
-----------
    docker build -t ai-detector-api .
    docker run -p 8000:8000 ai-detector-api
"""

import logging
import time
from contextlib import asynccontextmanager
from typing import Literal

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, field_validator

import model_loader

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Lifespan — load model once at startup, release on shutdown
# ---------------------------------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Starting up — loading model ...")
    model_loader.load_model()
    logger.info("Model ready.  API is live.")
    yield
    logger.info("Shutting down.")


# ---------------------------------------------------------------------------
# App instance
# ---------------------------------------------------------------------------
app = FastAPI(
    title="AI Text Detector API",
    description="Detects whether text was written by a human or generated by AI.",
    version="1.0.0",
    lifespan=lifespan,
)

# ---------------------------------------------------------------------------
# CORS — allow the React frontend (and Streamlit) to call this API
# Edit origins in production to only allow your actual domains
# ---------------------------------------------------------------------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],          # tighten in production: ["http://localhost:3000"]
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------

class PredictRequest(BaseModel):
    text: str = Field(..., min_length=10, description="Text to analyse.")
    mode: Literal["paragraph", "article"] = Field(
        "paragraph",
        description=(
            "'paragraph' scores the whole block as one unit.  "
            "'article' scores sentence-by-sentence and returns per-sentence results."
        ),
    )

    @field_validator("text")
    @classmethod
    def text_not_empty(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            raise ValueError("text must not be blank.")
        return stripped


class SentenceScore(BaseModel):
    sentence:  str
    ai_prob:   float
    label:     Literal["AI", "Human"]


class PredictResponse(BaseModel):
    label:            Literal["AI", "Human"]
    ai_prob:          float = Field(..., description="Probability the text is AI-generated (0–1).")
    human_prob:       float
    word_count:       int
    mode:             Literal["paragraph", "article"]
    sentence_scores:  list[SentenceScore] | None = Field(
        None,
        description="Only populated when mode='article'.",
    )
    latency_ms:       float = Field(..., description="Server-side inference time in milliseconds.")


class BatchPredictRequest(BaseModel):
    texts: list[str] = Field(..., min_length=1, max_length=20)
    mode:  Literal["paragraph", "article"] = "paragraph"


class BatchPredictResponse(BaseModel):
    results:    list[PredictResponse]
    total_ms:   float


class HealthResponse(BaseModel):
    status:      str
    model_ready: bool


class ModelInfoResponse(BaseModel):
    model_dir:    str
    device:       str
    id2label:     dict
    max_length:   int


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/health", response_model=HealthResponse, tags=["Meta"])
def health():
    """Liveness probe — used by Docker health checks and load balancers."""
    return {
        "status":      "ok",
        "model_ready": model_loader._model is not None,
    }


@app.get("/model/info", response_model=ModelInfoResponse, tags=["Meta"])
def model_info():
    """Return metadata about the loaded model checkpoint."""
    return {
        "model_dir":  str(model_loader.MODEL_DIR.resolve()),
        "device":     model_loader.DEVICE,
        "id2label":   model_loader.ID2LABEL,
        "max_length": model_loader.MAX_LENGTH,
    }


@app.post("/predict", response_model=PredictResponse, tags=["Inference"])
def predict(req: PredictRequest):
    """
    Main prediction endpoint.

    - **paragraph** mode — scores the whole text as one unit.  Fast; best for
      short passages (tweets, reviews, short essays).
    - **article** mode — splits into sentences, scores each one, returns
      per-sentence probabilities plus an aggregate document score.  Use this
      for news articles, essays, or any multi-paragraph input.
    """
    t0 = time.perf_counter()

    try:
        if req.mode == "paragraph":
            result = model_loader.predict_paragraph(req.text)
        else:
            result = model_loader.predict_article(req.text)
    except Exception as exc:
        logger.exception("Inference failed")
        raise HTTPException(status_code=500, detail=f"Inference error: {exc}")

    latency_ms = (time.perf_counter() - t0) * 1000

    return PredictResponse(
        label           = result["label"],
        ai_prob         = result["ai_prob"],
        human_prob      = result["human_prob"],
        word_count      = result["word_count"],
        mode            = req.mode,
        sentence_scores = result.get("sentence_scores"),   # None for paragraph mode
        latency_ms      = round(latency_ms, 2),
    )


@app.post("/predict/batch", response_model=BatchPredictResponse, tags=["Inference"])
def predict_batch(req: BatchPredictRequest):
    """
    Score up to 20 texts in a single request.
    Useful for bulk document processing or evaluation scripts.
    """
    t0 = time.perf_counter()
    results = []

    for text in req.texts:
        t1 = time.perf_counter()
        try:
            if req.mode == "paragraph":
                r = model_loader.predict_paragraph(text)
            else:
                r = model_loader.predict_article(text)
        except Exception as exc:
            logger.warning(f"Skipping text due to error: {exc}")
            continue

        latency_ms = (time.perf_counter() - t1) * 1000
        results.append(PredictResponse(
            label           = r["label"],
            ai_prob         = r["ai_prob"],
            human_prob      = r["human_prob"],
            word_count      = r["word_count"],
            mode            = req.mode,
            sentence_scores = r.get("sentence_scores"),
            latency_ms      = round(latency_ms, 2),
        ))

    total_ms = (time.perf_counter() - t0) * 1000
    return BatchPredictResponse(results=results, total_ms=round(total_ms, 2))